<?php
/**
 * Application: bPAD
 * Author: Bert Beentjes
 * Copyright: Copyright Bert Beentjes 2010-2014
 * http://www.bertbeentjes.nl, http://www.bpadcms.nl
 * 
 * This file is part of the bPAD content management system.
 * 
 * bPAD is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * bPAD is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with bPAD.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Names of layouts, styles and structures created and used by bPAD
 *
 */
class LSSNames {
    const STRUCTURE_CENTERED_TEXT = 'STRUCTURE_CENTERED_TEXT';
    const STRUCTURE_H1 = 'STRUCTURE_H1';
    const STRUCTURE_H2 = 'STRUCTURE_H2';
    const STRUCTURE_H3 = 'STRUCTURE_H3';
    const STRUCTURE_H4 = 'STRUCTURE_H4';
    const STRUCTURE_H5 = 'STRUCTURE_H5';
    const STRUCTURE_PARAGRAPH_START = 'STRUCTURE_PARAGRAPH_START';
    const STRUCTURE_PARAGRAPH_END = 'STRUCTURE_PARAGRAPH_END';
    const STRUCTURE_INTERNAL_LINK_START = 'STRUCTURE_INTERNAL_LINK_START';
    const STRUCTURE_INTERNAL_LINK_END = 'STRUCTURE_INTERNAL_LINK_END';
    const STRUCTURE_STRONG = 'STRUCTURE_STRONG';
    const STRUCTURE_ACCENT = 'STRUCTURE_ACCENT';
    const STRUCTURE_ITALIC = 'STRUCTURE_ITALIC';
    const STRUCTURE_EXTERNAL_LINK_START = 'STRUCTURE_EXTERNAL_LINK_START';
    const STRUCTURE_EXTERNAL_LINK_END = 'STRUCTURE_EXTERNAL_LINK_END';
    const STRUCTURE_LIST_ITEM = 'STRUCTURE_LIST_ITEM';
    const STRUCTURE_LIST_START = 'STRUCTURE_LIST_START';
    const STRUCTURE_LIST_END = 'STRUCTURE_LIST_END';
    const STRUCTURE_NEW_LINE = 'STRUCTURE_NEW_LINE';
    const STRUCTURE_BREADCRUMB = 'STRUCTURE_BREADCRUMB';
    const STRUCTURE_BREADCRUMB_SEPARATOR = 'STRUCTURE_BREADCRUMB_SEPARATOR';
    const STRUCTURE_LAZY_LOAD = 'STRUCTURE_LAZY_LOAD';
    const STRUCTURE_SEARCH_BOX = 'STRUCTURE_SEARCH_BOX';
    const STRUCTURE_INSTANCE_HEADER = 'STRUCTURE_INSTANCE_HEADER';
    const STRUCTURE_INSTANCE_SECTION = 'STRUCTURE_INSTANCE_SECTION';
    const STRUCTURE_CONFIG_BUTTON = 'STRUCTURE_CONFIG_BUTTON';
    const STRUCTURE_CONFIG_PANEL = 'STRUCTURE_CONFIG_PANEL';
    const STRUCTURE_BUTTON_TOGGLE = 'STRUCTURE_BUTTON_TOGGLE';
    const STRUCTURE_EDIT_BUTTON = 'STRUCTURE_EDIT_BUTTON';
    const STRUCTURE_EDIT_PANEL = 'STRUCTURE_EDIT_PANEL';
    const STRUCTURE_MOVE_BUTTON = 'STRUCTURE_MOVE_BUTTON';
    const STRUCTURE_MOVE_PANEL = 'STRUCTURE_MOVE_PANEL';
    const STRUCTURE_ERROR_MESSAGE = 'STRUCTURE_ERROR_MESSAGE';
    const STRUCTURE_MODAL = 'STRUCTURE_MODAL';
    const STRUCTURE_ADD_BUTTON = 'STRUCTURE_ADD_BUTTON';
    const STRUCTURE_ADD_PANEL = 'STRUCTURE_ADD_PANEL';
    const STRUCTURE_ADMIN_TEXT_INPUT = 'STRUCTURE_ADMIN_TEXT_INPUT';
    const STRUCTURE_ADMIN_TEXT_AREA = 'STRUCTURE_ADMIN_TEXT_AREA';
    const STRUCTURE_ADMIN_CHECKBOX = 'STRUCTURE_ADMIN_CHECKBOX';
    const STRUCTURE_ADMIN_COMBOBOX = 'STRUCTURE_ADMIN_COMBOBOX';
    const STRUCTURE_ADMIN_LISTBOX = 'STRUCTURE_ADMIN_LISTBOX';
    const STRUCTURE_ADMIN_LISTBOX_OPTION = 'STRUCTURE_ADMIN_LISTBOX_OPTION';
    const STRUCTURE_ADMIN_SUB_ITEM = 'STRUCTURE_ADMIN_SUB_ITEM';
    const STRUCTURE_ADMIN_SECTION_HEADER = 'STRUCTURE_ADMIN_SECTION_HEADER';
    const STRUCTURE_ADMIN_SECTION = 'STRUCTURE_ADMIN_SECTION';
    const STRUCTURE_ADMIN_SECTION_COLLAPSED = 'STRUCTURE_ADMIN_SECTION_COLLAPSED';
    const STRUCTURE_ADMIN_SEPARATOR = 'STRUCTURE_ADMIN_SEPARATOR';
    const STRUCTURE_ADMIN_FILE_INPUT = 'STRUCTURE_ADMIN_FILE_INPUT';
    const STRUCTURE_ADMIN_UPLOAD = 'STRUCTURE_ADMIN_UPLOAD';
    const STRUCTURE_ADMIN_BUTTON = 'STRUCTURE_ADMIN_BUTTON';
    const STRUCTURE_ADMIN_MAIN_BUTTON = 'STRUCTURE_ADMIN_MAIN_BUTTON';
    const STRUCTURE_ADMIN_MENU = 'STRUCTURE_ADMIN_MENU';
    const STRUCTURE_ADMIN_MENU_ITEM = 'STRUCTURE_ADMIN_MENU_ITEM';
    const STRUCTURE_ADMIN_BUTTON_GROUP = 'STRUCTURE_ADMIN_BUTTON_GROUP';
    const STRUCTURE_ADMIN_BUTTON_GROUP_ALT = 'STRUCTURE_ADMIN_BUTTON_GROUP_ALT';
}

?>
